package com.ksaakstudio.joanna.artistsearch.models;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import org.apache.commons.lang3.builder.ToStringBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Generated;

/**
 * While this was generated by jsonschema2pojo,
 * I added a few functions to make it parcelable.
 * I also have an oveloaded constructor to accomodate the artist
 * objects returned by the similar artists url.
 */
@Generated("org.jsonschema2pojo")
public class Artist implements Parcelable {

    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("listeners")
    @Expose
    private String listeners;
    @SerializedName("mbid")
    @Expose
    private String mbid;
    @SerializedName("match")
    @Expose
    private String match;
    @SerializedName("url")
    @Expose
    private String url;
    @SerializedName("streamable")
    @Expose
    private String streamable;
    @SerializedName("image")
    @Expose
    private List<Image> image = new ArrayList<Image>();
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    // static field used to regenerte object individually or as arrays.
    public static final Parcelable.Creator<Artist> CREATOR = new Parcelable.Creator<Artist>() {

        @Override
        public Artist createFromParcel(Parcel parcel) {
            return new Artist(parcel);
        }

        @Override
        public Artist[] newArray(int size) {
            return new Artist[size];
        }
    };

    public Artist(String name, String listeners, String mbid,
                  String url, String streamable, List<Image> image,
                  Map<String, Object> additionalProperties) {
        this.name = name;
        this.listeners = listeners;
        this.mbid = mbid;
        this.url = url;
        this.streamable = streamable;
        this.image = image;
        this.additionalProperties = additionalProperties;
    }

    public Artist(String name, String listeners, String mbid,
                  String url, String streamable, List<Image> image,
                  Map<String, Object> additionalProperties, String match) {
        this(name, listeners, mbid, url, streamable, image, additionalProperties);
        this.match = match;
    }

    public Artist(Parcel parcel) {
        name = parcel.readString();
        listeners = parcel.readString();
        mbid = parcel.readString();
        url = parcel.readString();
        streamable = parcel.readString();
        parcel.readTypedList(image, Image.CREATOR);
        additionalProperties = parcel.readHashMap(ClassLoader.getSystemClassLoader());

    }

    /**
     * 
     * @return
     *     The name
     */
    public String getName() {
        return name;
    }

    /**
     * 
     * @param name
     *     The name
     */
    public void setName(String name) {
        this.name = name;
    }

    public Artist withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * 
     * @return
     *     The listeners
     */
    public String getListeners() {
        return listeners;
    }

    /**
     * 
     * @param listeners
     *     The listeners
     */
    public void setListeners(String listeners) {
        this.listeners = listeners;
    }

    public Artist withListeners(String listeners) {
        this.listeners = listeners;
        return this;
    }

    /**
     * 
     * @return
     *     The mbid
     */
    public String getMbid() {
        return mbid;
    }

    /**
     * 
     * @param mbid
     *     The mbid
     */
    public void setMbid(String mbid) {
        this.mbid = mbid;
    }

    public Artist withMbid(String mbid) {
        this.mbid = mbid;
        return this;
    }

    /**
     *
     * @return
     *     The match
     */
    public String getMatch() {
        return match;
    }

    /**
     *
     * @param match
     *     The match
     */
    public void setMatch(String match) {
        this.match = match;
    }

    /**
     * 
     * @return
     *     The url
     */
    public String getUrl() {
        return url;
    }

    /**
     * 
     * @param url
     *     The url
     */
    public void setUrl(String url) {
        this.url = url;
    }

    public Artist withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * 
     * @return
     *     The streamable
     */
    public String getStreamable() {
        return streamable;
    }

    /**
     * 
     * @param streamable
     *     The streamable
     */
    public void setStreamable(String streamable) {
        this.streamable = streamable;
    }

    public Artist withStreamable(String streamable) {
        this.streamable = streamable;
        return this;
    }

    /**
     * 
     * @return
     *     The image
     */
    public List<Image> getImage() {
        return image;
    }

    /**
     * 
     * @param image
     *     The image
     */
    public void setImage(List<Image> image) {
        this.image = image;
    }

    public Artist withImage(List<Image> image) {
        this.image = image;
        return this;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    public Artist withAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
        return this;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.name);
        dest.writeString(this.listeners);
        dest.writeString(this.mbid);
        dest.writeString(this.url);
        dest.writeString(this.streamable);
        dest.writeTypedList(this.image);
        dest.writeMap(this.additionalProperties);
    }
}
